import { parseHTML } from "linkedom";
import { nowIso, slugify } from "../lib/io.mjs";

function cleanText(value) {
  return String(value ?? "").replace(/\s+/g, " ").trim();
}

function decodeEntities(value) {
  return String(value ?? "")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, "\"")
    .replace(/&#39;/g, "'");
}

function secondsToTimestamp(seconds) {
  const safe = Math.max(0, Number(seconds) || 0);
  const hours = Math.floor(safe / 3600);
  const minutes = Math.floor((safe % 3600) / 60);
  const secs = Math.floor(safe % 60);
  return [hours, minutes, secs].map((part) => String(part).padStart(2, "0")).join(":");
}

async function fetchWithTimeout(fetchImpl, url, timeoutMs = Number(process.env.AMKB_YOUTUBE_TIMEOUT_MS || 2500)) {
  if (fetchImpl !== fetch) {
    return fetchImpl(url);
  }

  return fetchImpl(url, {
    signal: AbortSignal.timeout(timeoutMs),
    redirect: "follow",
  });
}

export function normaliseYouTubeCaptionXml(xml) {
  const matches = [...xml.matchAll(/<text\b([^>]*)>([\s\S]*?)<\/text>/g)];
  return matches.map((match, index) => {
    const attrs = match[1];
    const text = cleanText(decodeEntities(match[2].replace(/<[^>]+>/g, "")));
    const start = Number(attrs.match(/\bstart="([^"]+)"/)?.[1] ?? 0);
    const duration = Number(attrs.match(/\bdur="([^"]+)"/)?.[1] ?? 0);

    return {
      id: `youtube-auto-${index + 1}`,
      start: secondsToTimestamp(start),
      end: duration ? secondsToTimestamp(start + duration) : undefined,
      text,
      source: "youtube-auto",
    };
  }).filter((segment) => segment.text);
}

export function parseCaptionTracksFromWatchHtml(html) {
  const tracklistMatch = html.match(/"captionTracks":(\[[\s\S]*?\])\s*,\s*"audioTracks"/);
  if (!tracklistMatch) {
    return [];
  }

  try {
    return JSON.parse(tracklistMatch[1]).map((track) => ({
      languageCode: track.languageCode,
      name: cleanText(track.name?.simpleText ?? track.name?.runs?.map((run) => run.text).join(" ") ?? ""),
      kind: track.kind,
      baseUrl: track.baseUrl,
      isAutoGenerated: track.kind === "asr" || /auto/i.test(track.name?.simpleText ?? ""),
    }));
  } catch {
    return [];
  }
}

export async function fetchYouTubeCaptionSegments(youtubeUrl, fetchImpl = fetch) {
  let watchResponse;
  try {
    watchResponse = await fetchWithTimeout(fetchImpl, youtubeUrl);
  } catch (error) {
    return {
      ok: false,
      reason: `YouTube watch fetch failed: ${error.message}`,
      segments: [],
    };
  }
  if (!watchResponse.ok) {
    return {
      ok: false,
      reason: `YouTube watch fetch failed with ${watchResponse.status}`,
      segments: [],
    };
  }

  const html = await watchResponse.text();
  const tracks = parseCaptionTracksFromWatchHtml(html);
  const selectedTrack =
    tracks.find((track) => track.languageCode?.startsWith("en") && track.isAutoGenerated) ??
    tracks.find((track) => track.languageCode?.startsWith("en")) ??
    tracks[0];

  if (!selectedTrack?.baseUrl) {
    return {
      ok: false,
      reason: "No YouTube captions available",
      segments: [],
    };
  }

  let captionsResponse;
  try {
    captionsResponse = await fetchWithTimeout(fetchImpl, selectedTrack.baseUrl);
  } catch (error) {
    return {
      ok: false,
      reason: `YouTube caption fetch failed: ${error.message}`,
      segments: [],
    };
  }
  if (!captionsResponse.ok) {
    return {
      ok: false,
      reason: `YouTube caption fetch failed with ${captionsResponse.status}`,
      segments: [],
    };
  }

  return {
    ok: true,
    source: {
      kind: "youtube-auto",
      url: youtubeUrl,
      fetchedAt: nowIso(),
      status: captionsResponse.status,
    },
    segments: normaliseYouTubeCaptionXml(await captionsResponse.text()),
  };
}

export function extractYouTubeVideoIdsFromSearchHtml(html) {
  const ids = [...html.matchAll(/"videoId":"([^"]+)"/g)].map((match) => match[1]);
  return [...new Set(ids)].slice(0, 5);
}

export async function searchYouTubeForEpisode(episode, fetchImpl = fetch) {
  const query = `${episode.title} ${episode.guest} Acquiring Minds`;
  let response;
  try {
    response = await fetchWithTimeout(
      fetchImpl,
      `https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`,
    );
  } catch (error) {
    return {
      ok: false,
      reason: `YouTube search failed: ${error.message}`,
    };
  }

  if (!response.ok) {
    return {
      ok: false,
      reason: `YouTube search failed with ${response.status}`,
    };
  }

  const ids = extractYouTubeVideoIdsFromSearchHtml(await response.text());
  if (ids.length !== 1) {
    return {
      ok: false,
      reason: ids.length === 0 ? "No YouTube search results" : "Ambiguous YouTube search results",
      candidates: ids.map((id) => `https://www.youtube.com/watch?v=${id}`),
    };
  }

  return {
    ok: true,
    youtubeUrl: `https://www.youtube.com/watch?v=${ids[0]}`,
    id: slugify(ids[0]),
  };
}
